### ISSUE TITLE
Update Suggestion: Add A Waiting On Section to Job MOC

### ISSUE THREAD

**Issue by YvonneBeirneFitzGerald** [universvm/obsidian-job-dashboard#3]
Thank you for sharing this template it is fantastic!

I wanted to add a Waiting For Response section for applications that I have applied for but have not received a response.  I copy the active section to a new section.  I then updated the where line to :

 "where Status != "Rejected" and row["Date Applied"] >= date(2024-01-01) and row["Last Round"] = "Online Application""

This assumes that Jobs with Online Applications has not received a response. My number is off from the graph  (Issue 2), which means this might not be the best approach, and just a bad user.

**Comment by DrLeucine** [comment]
Hi @YvonneBeirneFitzGerald , 

Thanks for your feedback and trying this out. At the moment we have something like this called "Waiting" which are active applications with history "None". Does this address your problem by any chance? 

I think it can definitely be more intuitive. I'd like the flow to be defined neatly somehow but I haven't figured out a good way of doing this

**Comment by YvonneBeirneFitzGerald** [comment]
@universvm Thanks for getting back to me.  I will give the History = "None' a whirl and see how it works out.  I am prepping for the upcoming holiday so I might not get to try it out until the early part of next week.  I share with you what works.

**Comment by DrLeucine** [comment]
Hi @YvonneBeirneFitzGerald I added the feature. Apologies I think I initially misunderstood what you were asking.
