### ISSUE TITLE
Parsing Error Mermaid

### ISSUE THREAD

**Issue by salwinat0r** [universvm/obsidian-job-dashboard#4]
The code gave the following error

```
Error parsing Mermaid diagram!

Parse error on line 1:
sankey-beta
-----------^
Expecting 'NEWLINE', got 'EOF'
```

**Comment by salwinat0r** [comment]
Yes, same as the one in the repo

**Comment by universvm** [comment]
@salwinat0r I just downloaded the zip file and opened it in Obsidian. I cannot replicate.

<img width="1494" alt="Screenshot 2024-12-09 at 10 26 21" src="https://github.com/user-attachments/assets/e86c46e5-14fe-47ee-bd26-7fdd2c11fd5c">

 Could you check that the plugins are active? They are in a hidden folder. 

If you open the current repo as a vault you shouldn't have any problems

**Comment by salwinat0r** [comment]
Got it! Opening it as a vault works without any issues. New to Mermaid, any tips on how I could make this work on my personal vault as I would it be useful if I could edit it from my phone too!

**Comment by universvm** [comment]
> Got it! Opening it as a vault works without any issues. New to Mermaid, any tips on how I could make this work on my personal vault as I would it be useful if I could edit it from my phone too!

Of course! The only thing that's missing when you copy and paste is the hidden folder. Obsidian keeps all the plugins in a hidden folder. 

To use this plugin you need to install these:

- Dataview
- Templater

I'll make a note to improve the documentation.

**Comment by salwinat0r** [comment]
It worked! Replaced the dataview and templates-obsidian plugin from the repo to my vault's plugin folder. Amazing work on the dashboard. Cheers
